trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: WiseOldTurtleSP  # Variable group where secrets are stored
  - template: variables.yaml # Reusable YAML templates which define common configurations / reduce duplication.

stages:
  - stage: DeployLZ
    jobs:
      - job: DeployCoreResources
        displayName: 'Run Terraform Commands'
        steps:
          - script: |
              cd LZ-Terraform/networking
              terraform init
              terraform plan
              terraform apply -auto-approve
            displayName: 'Run Terraform for Networking'
            env:
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_TENANT_ID: $(ARM_TENANT_ID)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)

          - script: |
              cd LZ-Terraform/security
              terraform init
              terraform plan
              terraform apply -auto-approve
            displayName: 'Run Terraform for Security'
            env:
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_TENANT_ID: $(ARM_TENANT_ID)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)

          - script: |
              cd LZ-Terraform/policy
              terraform init
              terraform plan
              terraform apply -auto-approve
            displayName: 'Run Terraform for Policy'
            env:
              ARM_CLIENT_ID: $(ARM_CLIENT_ID)
              ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
              ARM_TENANT_ID: $(ARM_TENANT_ID)
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
