trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: WiseOldTurtleSP  # Variable group where secrets are stored
  - template: variables.yml # reusable YAML templates which define common configurations / reduce duplication.

stages:
  - stage: Deploy
    jobs:
      - job: TerraformJob
        displayName: 'Run Terraform Commands'
        steps:
          - script: |
              cd networking
              terraform init
              terraform plan
              terraform apply -auto-approve
            displayName: 'Run Terraform for Networking'

          - script: |
              cd security
              terraform init
              terraform plan
              terraform apply -auto-approve
            displayName: 'Run Terraform for Security'

          - script: |
              cd policy
              terraform init
              terraform plan
              terraform apply -auto-approve
            displayName: 'Run Terraform for Policy'
